TELEFON1 = "+998993342035"
TELEFON2 = "+998704902025"
INSTAGRAM = "https://instagram.com/togtagi"

MATNLAR = {
    "uz": {
        "til_tanlash": "Tilni tanlang:",
        "xush_kelibsiz": "Tog Tagi Resort ga xush kelibsiz!\n\nShohimardon tog'lari bag'rida dam oling!\n\n🌊 Soy | 💦 Sharshara | 🍽 Oshxona\n🔥 Mangal | 🛖 Tapchanlar | 🚗 Parking\n\n📍 Ko'lqubondan 300 metr pastda\n\n📞 {tel1}  |  {tel2}",
        "bron_btn": "🛏 Xona bron qilish",
        "bosh_xonalar_btn": "📅 Bo'sh xonalar",
        "galereya_btn": "🖼 Galereya",
        "xizmatlar_btn": "🌿 Xizmatlar",
        "manzil_btn": "📍 Manzil",
        "boglanish_btn": "📞 Bog'lanish",
        "mening_bronlarim_btn": "🎫 Mening bronlarim",
        "bosh_menyu_btn": "🏠 Bosh menyu",
        "necha_kishi": "👥 Nechta kishi kelmoqchisiz?",
        "kimlar": "👥 Kimlar bilan kelmoqchisiz?",
        "oila_btn": "👨‍👩‍👧‍👦 Oila bilan",
        "dostlar_btn": "👬 Do'stlar / Erkaklar",
        "qaysi_sana": "📅 Qaysi sanada kelmoqchisiz?",
        "necha_kun": "🌙 Necha kun turmoqchisiz?",
        "sana_tanlang": "👇 Sanani tanlang (30 kun):",
        "ism": "👤 Ismingizni kiriting:",
        "telefon": "📞 Telefon raqamingizni yuboring:\n\nYoki kiriting: +998901234567",
        "kontakt_btn": "📱 Kontaktni yuborish",
        "tasdiq_btn": "✅ Tasdiqlash",
        "bekor_btn": "❌ Bekor",
        "bron_yuborildi": "⏳ So'rovingiz qabul qilindi!\n\nBron ID: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} kishi\n💰 {narx} so'm\n\nAdmin tasdiqlashini kuting.\n📞 {tel}",
        "bron_tasdiqlandi": "✅ Broningiz tasdiqlandi!\n\nBron ID: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} kishi\n💰 {narx} so'm\n\nKelishingizni kutamiz!\n📞 {tel}",
        "bron_rad": "❌ Bron #{bid} rad etildi.\nBog'laning: {tel}",
        "bron_bekor": "❌ Bron #{bid} bekor qilindi.",
        "1kun_eslatma": "📅 Eslatma!\n\nErtaga resortga kelasiz:\nBron #{bid}\n🛏 {xona}\n📅 {sana}\n\nSavollar: {tel}",
        "vaqt_tugaydi": "⏰ Bugun 12:00 da xonadagi vaqtingiz tugaydi.\nIltimos, xonani bo'shating.\n\n🛖 Tapchanlardan kechgacha foydalanishingiz mumkin!\n📞 {tel}",
        "mos_xona": "✅ Sizga mos variant:",
        "barcha_bosh": "📋 Barcha bo'sh xonalar",
        "xona_yoq": "❌ Bu sanada mos bo'sh xona yo'q.\n\nBog'laning: {tel}",
        "ortiqcha_kishi": "⚠️ Diqqat! {xona} da {sigim} joy bor, siz {kishi} kishisiz.\n1 kishi ko'p — u qo'shimcha joy topishi kerak.",
        "xizmatlar_matn": "🌿 Tog' Tagi Resort Xizmatlari:\n\n🌊 Soy bo'yi\n💦 Sharshara\n🍽 Oshxona (o'zingiz pishirasiz)\n🔥 Mangal\n🥩 Shashlik\n📶 WiFi\n📺 Televizor\n🛏 Yotoq joylar\n🛖 Tapchanlar\n🚗 Bepul parking\n🌿 Yashil tabiat\n\n📞 {tel1}\n📞 {tel2}",
        "manzil_matn": "📍 Tog' Tagi Resort:\n\nShohimardon, Farg'ona viloyati\nKo'lqubondan 300 metr pastda\n\n📞 {tel1}\n📞 {tel2}",
        "boglanish_matn": "📞 Bog'lanish:\n\n📱 {tel1}\n📱 {tel2}\n📸 @togtagi\n⏰ 24/7",
        "xato": "⚠️ Xatolik yuz berdi.\n\nBog'laning:\n📞 {tel1}\n📞 {tel2}",
        "til_btn": "🇺🇿 O'zbek (lotin)",
        "galereya_yoq": "📸 Hozircha rasm/video yo'q.",
        "bronlarim_yoq": "Hozircha bronlaringiz yo'q.",
    },
    "uz_kril": {
        "til_tanlash": "Tilни танланг:",
        "xush_kelibsiz": "Тог Таги Резортга хуш келибсиз!\n\nШоҳимардон тоғлари бағрида дам олинг!\n\n🌊 Соy | 💦 Шаршара | 🍽 Ошхона\n🔥 Мангал | 🛖 Тапчанлар | 🚗 Паркинг\n\n📍 Кўлқубондан 300 метр пастда\n\n📞 {tel1}  |  {tel2}",
        "bron_btn": "🛏 Хона брон қилиш",
        "bosh_xonalar_btn": "📅 Бўш хоналар",
        "galereya_btn": "🖼 Галерея",
        "xizmatlar_btn": "🌿 Хизматлар",
        "manzil_btn": "📍 Манзил",
        "boglanish_btn": "📞 Боғланиш",
        "mening_bronlarim_btn": "🎫 Менинг бронларим",
        "bosh_menyu_btn": "🏠 Бош меню",
        "necha_kishi": "👥 Неча киши келмоқчисиз?",
        "kimlar": "👥 Кимлар билан келмоқчисиз?",
        "oila_btn": "👨‍👩‍👧‍👦 Оила билан",
        "dostlar_btn": "👬 Дўстлар / Эркаклар",
        "qaysi_sana": "📅 Қайси санада келмоқчисиз?",
        "necha_kun": "🌙 Неча кун турмоқчисиз?",
        "sana_tanlang": "👇 Санани танланг (30 кун):",
        "ism": "👤 Исмингизни киритинг:",
        "telefon": "📞 Телефон рақамингизни юборинг:\n\nЁки киритинг: +998901234567",
        "kontakt_btn": "📱 Контактни юбориш",
        "tasdiq_btn": "✅ Тасдиқлаш",
        "bekor_btn": "❌ Бекор",
        "bron_yuborildi": "⏳ Сўровингиз қабул қилинди!\n\nБрон ID: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} киши\n💰 {narx} сўм\n\nАдмин тасдиқлашини кутинг.\n📞 {tel}",
        "bron_tasdiqlandi": "✅ Бронингиз тасдиқланди!\n\nБрон ID: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} киши\n💰 {narx} сўм\n\nКелишингизни кутамиз!\n📞 {tel}",
        "bron_rad": "❌ Брон #{bid} рад этилди.\nБоғланинг: {tel}",
        "bron_bekor": "❌ Брон #{bid} бекор қилинди.",
        "1kun_eslatma": "📅 Эслатма!\n\nЭртага резортга келасиз:\nБрон #{bid}\n🛏 {xona}\n📅 {sana}\n\nСаволлар: {tel}",
        "vaqt_tugaydi": "⏰ Бугун 12:00 да хонадаги вақтингиз тугайди.\nИлтимос, хонани бўшатинг.\n\n🛖 Тапчанлардан кечгача фойдаланишингиз мумкин!\n📞 {tel}",
        "mos_xona": "✅ Сизга мос вариант:",
        "barcha_bosh": "📋 Барча бўш хоналар",
        "xona_yoq": "❌ Бу санада мос бўш хона йўқ.\n\nБоғланинг: {tel}",
        "ortiqcha_kishi": "⚠️ Диqqat! {xona} да {sigim} жой бор, сиз {kishi} кишисиз.\n1 киши кўп — у қўшимча жой топиши керак.",
        "xizmatlar_matn": "🌿 Тог Таги Резорт Хизматлари:\n\n🌊 Соy бўйи\n💦 Шаршара\n🍽 Ошхона (ўзингиз пишрасиз)\n🔥 Мангал\n🥩 Шашлик\n📶 WiFi\n📺 Телевизор\n🛏 Ётоқ жойлар\n🛖 Тапчанлар\n🚗 Бепул паркинг\n🌿 Яшил табиат\n\n📞 {tel1}\n📞 {tel2}",
        "manzil_matn": "📍 Тог Таги Резорт:\n\nШоҳимардон, Фарғона вилояти\nКўлқубондан 300 метр пастда\n\n📞 {tel1}\n📞 {tel2}",
        "boglanish_matn": "📞 Боғланиш:\n\n📱 {tel1}\n📱 {tel2}\n📸 @togtagi\n⏰ 24/7",
        "xato": "⚠️ Хатолик юз берди.\n\nБоғланинг:\n📞 {tel1}\n📞 {tel2}",
        "til_btn": "🇺🇿 Узбек (кирил)",
        "galereya_yoq": "📸 Ҳозирча расм/видео йўқ.",
        "bronlarim_yoq": "Ҳозирча бронларингиз йўқ.",
    },
    "ru": {
        "til_tanlash": "Выберите язык:",
        "xush_kelibsiz": "Добро пожаловать в Tog' Tagi Resort!\n\nОтдохните в горах Шахимардона!\n\n🌊 У реки | 💦 Водопад | 🍽 Кухня\n🔥 Мангал | 🛖 Беседки | 🚗 Парковка\n\n📍 В 300 метрах ниже Кулькубона\n\n📞 {tel1}  |  {tel2}",
        "bron_btn": "🛏 Забронировать",
        "bosh_xonalar_btn": "📅 Свободные номера",
        "galereya_btn": "🖼 Галерея",
        "xizmatlar_btn": "🌿 Услуги",
        "manzil_btn": "📍 Адрес",
        "boglanish_btn": "📞 Контакты",
        "mening_bronlarim_btn": "🎫 Мои брони",
        "bosh_menyu_btn": "🏠 Главное меню",
        "necha_kishi": "👥 Сколько человек приедет?",
        "kimlar": "👥 С кем приедете?",
        "oila_btn": "👨‍👩‍👧‍👦 С семьёй",
        "dostlar_btn": "👬 С друзьями",
        "qaysi_sana": "📅 На какую дату?",
        "necha_kun": "🌙 На сколько ночей?",
        "sana_tanlang": "👇 Выберите дату (30 дней):",
        "ism": "👤 Введите ваше имя:",
        "telefon": "📞 Отправьте номер телефона:\n\nИли введите: +998901234567",
        "kontakt_btn": "📱 Отправить контакт",
        "tasdiq_btn": "✅ Подтвердить",
        "bekor_btn": "❌ Отмена",
        "bron_yuborildi": "⏳ Заявка принята!\n\nID брони: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} чел.\n💰 {narx} сум\n\nОжидайте подтверждения.\n📞 {tel}",
        "bron_tasdiqlandi": "✅ Бронь подтверждена!\n\nID брони: #{bid}\n🛏 {xona}\n📅 {sana} — {tugash}\n👥 {kishi} чел.\n💰 {narx} сум\n\nЖдём вас!\n📞 {tel}",
        "bron_rad": "❌ Бронь #{bid} отклонена.\nСвяжитесь: {tel}",
        "bron_bekor": "❌ Бронь #{bid} отменена.",
        "1kun_eslatma": "📅 Напоминание!\n\nЗавтра вы приедете в resort:\nБронь #{bid}\n🛏 {xona}\n📅 {sana}\n\nВопросы: {tel}",
        "vaqt_tugaydi": "⏰ Сегодня в 12:00 время в номере заканчивается.\nПожалуйста, освободите номер.\n\n🛖 Беседки до вечера в вашем распоряжении!\n📞 {tel}",
        "mos_xona": "✅ Подходящий вариант:",
        "barcha_bosh": "📋 Все свободные номера",
        "xona_yoq": "❌ На эту дату нет подходящих номеров.\n\nСвяжитесь: {tel}",
        "ortiqcha_kishi": "⚠️ Внимание! В {xona} мест {sigim}, вас {kishi}.\n1 человек лишний — нужно дополнительное место.",
        "xizmatlar_matn": "🌿 Услуги Tog' Tagi Resort:\n\n🌊 Берег реки\n💦 Водопад\n🍽 Кухня (готовите сами)\n🔥 Мангал\n🥩 Шашлык\n📶 WiFi\n📺 Телевизор\n🛏 Спальные места\n🛖 Беседки\n🚗 Бесплатная парковка\n🌿 Природа\n\n📞 {tel1}\n📞 {tel2}",
        "manzil_matn": "📍 Tog' Tagi Resort:\n\nШахимардон, Ферганская область\nВ 300 метрах ниже Кулькубона\n\n📞 {tel1}\n📞 {tel2}",
        "boglanish_matn": "📞 Контакты:\n\n📱 {tel1}\n📱 {tel2}\n📸 @togtagi\n⏰ 24/7",
        "xato": "⚠️ Произошла ошибка.\n\nСвяжитесь:\n📞 {tel1}\n📞 {tel2}",
        "til_btn": "🇷🇺 Русский",
        "galereya_yoq": "📸 Пока нет фото/видео.",
        "bronlarim_yoq": "У вас пока нет броней.",
    }
}

def t(uid, kalit, **kwargs):
    from database import get_til
    til = get_til(uid) or "uz"
    matn = MATNLAR.get(til, MATNLAR["uz"]).get(kalit, kalit)
    try:
        return matn.format(tel1=TELEFON1, tel2=TELEFON2, tel=TELEFON1, **kwargs)
    except:
        return matn
